profile:	
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Balamta.tsv
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Ratanchha.tsv
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Aaptar.tsv
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Halesi.tsv
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Hadunge.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Santang.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Tekunala.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Guthitar.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Khalde.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Hatiya.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Khoku.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Lungin.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Thidingkha.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Timma.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Okhre.tsv
	cut -f1,2 etc/orthography-Belhare.tsv > etc/orthography/Belhare.tsv
	cut -f1,2 etc/orthography-Belhare.tsv > etc/orthography/Piple.tsv
	cut -f1,2 etc/orthography-Belhare.tsv > etc/orthography/GuthitarB.tsv
	cut -f1,2 etc/orthography-Belhare.tsv > etc/orthography/Rudrabari.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/ChaudhariTole.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Mulgaun.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Nangchhuwa.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Mangthana.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Chambak.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Barbhanjyang.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Gairi.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Pakha.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Pokla.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Sukeahal.tsv
	cut -f1,2 etc/orthography-Dhimal.tsv > etc/orthography/DhimalWest.tsv
	cut -f1,2 etc/orthography-Dhimal.tsv > etc/orthography/DhimalEast.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Bartole.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Dandatole.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Tharpu.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Chaukibari.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Bastim.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Mandre.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Barpak1.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Barpak2.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Laprak.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Gumda.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Yarsa.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Chhetrapa.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Sikri.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Kharoban.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/RatmateKot.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Pokhara.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Sikles.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Khasur.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Bhujung.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Sirubari.tsv
