profile:	
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Chamling-Balamta.tsv
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Chamling-Ratanchha.tsv
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Chamling-Aaptar.tsv
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Chamling-Halesi.tsv
	cut -f1,2 etc/orthography-Chamling.tsv > etc/orthography/Chamling-Hadunge.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Athpahariya-Santang.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Athpahariya-Tekunala.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Athpahariya-Guthitar.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Athpahariya-Khalde.tsv
	cut -f1,2 etc/orthography-Athpahariya.tsv > etc/orthography/Athpahariya-Hatiya.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Bantawa-Khoku.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Bantawa-Lungin.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Bantawa-Thidingkha.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Bantawa-Timma.tsv
	cut -f1,2 etc/orthography-Bantawa.tsv > etc/orthography/Bantawa-Okhre.tsv
	cut -f1,2 etc/orthography-Belhare.tsv > etc/orthography/Belhare-Belhare.tsv
	cut -f1,2 etc/orthography-Belhare.tsv > etc/orthography/Belhare-Piple.tsv
	cut -f1,2 etc/orthography-Belhare.tsv > etc/orthography/Belhare-Guthitar.tsv
	cut -f1,2 etc/orthography-Belhare.tsv > etc/orthography/Belhare-Rudrabari.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Chintang-ChaudhariTole.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Chintang-Mulgaun.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Chintang-Nangchhuwa.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Chintang-Mangthana.tsv
	cut -f1,2 etc/orthography-Chintang.tsv > etc/orthography/Chintang-Chambak.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Chulung-Barbhanjyang.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Chulung-Gairi.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Chulung-Pakha.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Chulung-Pokla.tsv
	cut -f1,2 etc/orthography-Chulung.tsv > etc/orthography/Chulung-Sukeahal.tsv
	cut -f1,2 etc/orthography-Dhimal.tsv > etc/orthography/Dhimal-West.tsv
	cut -f1,2 etc/orthography-Dhimal.tsv > etc/orthography/Dhimal-East.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Dulung-Bartole.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Dulung-Dandatole.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Dulung-Tharpu.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Dulung-Chaukibari.tsv
	cut -f1,2 etc/orthography-Dulung.tsv > etc/orthography/Dulung-Bastim.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Ghale-Gurung-Mandre.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Ghale-Gurung-Barpak1.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Ghale-Gurung-Barpak2.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Ghale-Gurung-Laprak.tsv
	cut -f1,2 etc/orthography-Ghale-Gurung.tsv > etc/orthography/Ghale-Gurung-Gumda.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Jirel-Yarsa.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Jirel-Chhetrapa.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Jirel-Sikri.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Jirel-Kharoban.tsv
	cut -f1,2 etc/orthography-Jirel.tsv > etc/orthography/Jirel-RatmateKot.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Gurung-Pokhara.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Gurung-Sikles.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Gurung-Khasur.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Gurung-Bhujung.tsv
	cut -f1,2 etc/orthography-Gurung.tsv > etc/orthography/Gurung-Sirubari.tsv
server:
	datasette NLS.sqlite --static assets:app/static-files/ --metadata app/metadata.yaml --template-dir="app/templates/" -p 8002 --plugins-dir=app/ --setting truncate_cells_html 0

